const categories=[['Wszystko','✦'],['Motoryzacja','🚗'],['Nieruchomości','🏠'],['Praca','💼'],['Dom i ogród','🛋️'],['Elektronika','📱'],['Usługi','🛠️'],['Dla dzieci','🧸']];
const events=[
 {title:'Letni koncert na legnickim Rynku',date:'2 sierpnia, 19:00',tag:'Wydarzenie',image:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&q=80'},
 {title:'Weekendowy targ lokalnych produktów',date:'3 sierpnia, 9:00',tag:'Lokalnie',image:'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=900&q=80'},
 {title:'Nowa strefa rekreacyjna dla mieszkańców',date:'Aktualność miejska',tag:'Aktualność',image:'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=900&q=80'},
 {title:'Rodzinny piknik w parku miejskim',date:'10 sierpnia, 12:00',tag:'Rodzina',image:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=80'}
];
const seedListings=[
 {id:1,title:'Rower miejski w bardzo dobrym stanie',category:'Motoryzacja',price:850,location:'Legnica, Centrum',time:'dzisiaj',image:'https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=900&q=80',description:'Zadbany rower miejski, gotowy do jazdy. Odbiór osobisty w centrum Legnicy.'},
 {id:2,title:'Mieszkanie 2 pokoje, 48 m²',category:'Nieruchomości',price:349000,location:'Legnica, Tarninów',time:'dzisiaj',image:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80',description:'Jasne mieszkanie po remoncie, dwa pokoje, osobna kuchnia i balkon.'},
 {id:3,title:'iPhone 14 128 GB',category:'Elektronika',price:2450,location:'Legnica',time:'wczoraj',image:'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=900&q=80',description:'Telefon w pełni sprawny, bateria 89%, komplet z pudełkiem.'},
 {id:4,title:'Stół dębowy z czterema krzesłami',category:'Dom i ogród',price:1200,location:'Legnica, Piekary',time:'wczoraj',image:'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=900&q=80',description:'Solidny zestaw z litego drewna. Możliwy transport na terenie miasta.'},
 {id:5,title:'Pomoc przy remontach i wykończeniach',category:'Usługi',price:80,location:'Legnica i okolice',time:'2 dni temu',image:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=80',description:'Malowanie, gładzie, panele i drobne naprawy. Cena za godzinę pracy.'},
 {id:6,title:'Opiekunka do dziecka — popołudnia',category:'Praca',price:30,location:'Legnica',time:'2 dni temu',image:'https://images.unsplash.com/photo-1543342384-1f1350e27861?auto=format&fit=crop&w=900&q=80',description:'Szukamy odpowiedzialnej osoby do opieki nad dzieckiem kilka razy w tygodniu.'},
 {id:7,title:'Wózek dziecięcy 3w1',category:'Dla dzieci',price:650,location:'Legnica, Kopernik',time:'3 dni temu',image:'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=900&q=80',description:'Kompletny zestaw w bardzo dobrym stanie, używany przez jedno dziecko.'},
 {id:8,title:'Kosiarka elektryczna',category:'Dom i ogród',price:420,location:'Kunice',time:'3 dni temu',image:'https://images.unsplash.com/photo-1599685315640-9ceab2f581ca?auto=format&fit=crop&w=900&q=80',description:'Sprawna kosiarka z koszem, szerokość robocza 38 cm.'}
];
let listings=JSON.parse(localStorage.getItem('lr-listings')||'null')||seedListings;
let favorites=new Set(JSON.parse(localStorage.getItem('lr-favorites')||'[]'));
let activeCategory='Wszystko';let searchTerm='';
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:0}).format(n);
function renderDate(){const d=new Date();$('#current-date').textContent=new Intl.DateTimeFormat('pl-PL',{day:'numeric',month:'long'}).format(d);$('#current-day').textContent=new Intl.DateTimeFormat('pl-PL',{weekday:'long'}).format(d);$('#current-time').textContent=d.toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'});}renderDate();setInterval(renderDate,30000);
function renderCategories(){const root=$('#category-grid');root.innerHTML=categories.map(([name,icon])=>`<button class="category-card ${name===activeCategory?'active':''}" data-category="${name}"><span class="category-icon">${icon}</span><strong>${name}</strong><small>${name==='Wszystko'?listings.length:listings.filter(x=>x.category===name).length} ofert</small></button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;renderCategories();renderFilters();renderListings();document.querySelector('#ads-title').scrollIntoView({behavior:'smooth'});});}
function renderEvents(){$('#events-list').innerHTML=events.map(e=>`<article class="event-card"><div class="event-image" style="background-image:url('${e.image}')"><span class="event-tag">${e.tag}</span></div><div class="event-body"><h3>${e.title}</h3><div class="event-meta">${e.date} · Legnica</div></div></article>`).join('');}
function renderFilters(){const names=['Wszystko',...categories.slice(1).map(x=>x[0])];$('#filter-row').innerHTML=names.map(n=>`<button class="filter-chip ${n===activeCategory?'active':''}" data-filter="${n}">${n}</button>`).join('');document.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.filter;renderCategories();renderFilters();renderListings();});}
function filtered(){return listings.filter(x=>(activeCategory==='Wszystko'||x.category===activeCategory)&&(`${x.title} ${x.description} ${x.location}`.toLowerCase().includes(searchTerm)));}
function renderListings(){const data=filtered();$('#empty-state').hidden=data.length>0;$('#listing-grid').innerHTML=data.map(x=>`<article class="listing-card" data-id="${x.id}"><img class="listing-image" src="${x.image}" alt="${x.title}"><button class="favorite-button ${favorites.has(x.id)?'active':''}" data-favorite="${x.id}" aria-label="Dodaj do ulubionych">${favorites.has(x.id)?'♥':'♡'}</button><div class="listing-body"><span class="listing-category">${x.category}</span><h3>${x.title}</h3><div class="listing-price">${money(x.price)}</div><div class="listing-meta"><span>${x.location}</span><span>${x.time}</span></div></div></article>`).join('');document.querySelectorAll('.listing-card').forEach(card=>card.onclick=e=>{if(e.target.closest('[data-favorite]'))return;openDetails(Number(card.dataset.id));});document.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=Number(b.dataset.favorite);favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('lr-favorites',JSON.stringify([...favorites]));renderListings();showToast(favorites.has(id)?'Dodano do ulubionych':'Usunięto z ulubionych');});}
function openDetails(id){const x=listings.find(i=>i.id===id);if(!x)return;$('#details-image').src=x.image;$('#details-image').alt=x.title;$('#details-category').textContent=x.category;$('#details-title').textContent=x.title;$('#details-price').textContent=money(x.price);$('#details-description').textContent=x.description;$('#details-location').textContent=`📍 ${x.location}`;$('#details-dialog').showModal();}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200);}
$('#search-input').addEventListener('input',e=>{searchTerm=e.target.value.trim().toLowerCase();renderListings();});$('#search-form').addEventListener('submit',e=>e.preventDefault());$('#clear-search').onclick=()=>{$('#search-input').value='';searchTerm='';renderListings();};
$('#open-ad').onclick=()=>$('#ad-dialog').showModal();$('#profile-button').onclick=()=>$('#login-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
$('#ad-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const item={id:Date.now(),title:f.get('title'),category:f.get('category'),price:Number(f.get('price')),location:f.get('location'),image:f.get('image')||'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=80',description:f.get('description'),time:'przed chwilą'};listings.unshift(item);localStorage.setItem('lr-listings',JSON.stringify(listings));e.currentTarget.reset();$('#ad-dialog').close();activeCategory='Wszystko';renderCategories();renderFilters();renderListings();showToast('Ogłoszenie zostało dodane');});
$('#login-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const user={name:f.get('name'),email:f.get('email')};localStorage.setItem('lr-user',JSON.stringify(user));$('#profile-button').textContent=user.name;$('#login-dialog').close();showToast(`Witaj, ${user.name}`);});
const savedUser=JSON.parse(localStorage.getItem('lr-user')||'null');if(savedUser)$('#profile-button').textContent=savedUser.name;
$('#contact-seller').onclick=()=>showToast('Moduł wiadomości będzie kolejnym etapem');
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-nav]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const n=b.dataset.nav;if(n==='home')scrollTo({top:0,behavior:'smooth'});if(n==='categories')$('.category-section').scrollIntoView({behavior:'smooth'});if(n==='messages')showToast('Wiadomości będą dostępne w kolejnym etapie');if(n==='profile')$('#login-dialog').showModal();});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='all'){$('#ads-title').scrollIntoView({behavior:'smooth'});activeCategory='Wszystko';renderCategories();renderFilters();renderListings();}else showToast('Pełny kalendarz wydarzeń będzie kolejnym widokiem');});
const adCategory=$('#ad-category');adCategory.innerHTML=categories.slice(1).map(([n])=>`<option>${n}</option>`).join('');
renderCategories();renderEvents();renderFilters();renderListings();